# Generated by Django 6.0.3 on 2026-04-12 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('cover_image_id', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GamePlatformRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('date_format', models.CharField(blank=True, choices=[('YYYYMMDD', 'Exact date'), ('YYYYMM', 'Year and month'), ('YYYY', 'Year'), ('YYYYQ1', 'Year and quarter 1'), ('YYYYQ2', 'Year and quarter 2'), ('YYYYQ3', 'Year and quarter 3'), ('YYYYQ4', 'Year and quarter 4'), ('TBD', 'To be determined')], max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='games.game')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='games.platform')),
            ],
            options={
                'verbose_name': 'Game release',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='games', through='games.GamePlatformRelease', to='games.platform'),
        ),
        migrations.AddConstraint(
            model_name='gameplatformrelease',
            constraint=models.UniqueConstraint(fields=('game', 'platform'), name='unique_game_platform'),
        ),
    ]
