# Generated by Django 6.0.3 on 2026-04-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_webhookevent_game_hypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplatformrelease',
            name='igdb_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
