# Generated by Django 6.0.3 on 2026-04-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gameplatformrelease_igdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplatformrelease',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplatformrelease',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplatformrelease',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
