# Generated by Django 6.0.3 on 2026-04-20 06:52

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_gameplatformrelease_day_gameplatformrelease_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='game',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='games_game_search__957095_gin'),
        ),
    ]
