# Generated by Django 6.0.3 on 2026-04-28 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_usergame_game_alter_usergame_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usergame',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='unique_user_game'),
        ),
    ]
