# Generated by Django 6.0.3 on 2026-05-01 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_releasedateformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplatformrelease',
            name='date_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.releasedateformat'),
        ),
    ]
