# Generated by Django 6.0.3 on 2026-05-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_alter_gameplatformrelease_date_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameplatformrelease',
            options={'ordering': ['date'], 'verbose_name': 'Game release'},
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
